### ISSUE TITLE
(Docker) No Configuration file provided: not found

### ISSUE THREAD

**Issue by yandy-r** [rfgamaral/PlexMusicRatingsSync#7]
When attempting to run the script with docker I get the error mentioned in the title.

`No configuration file provided: not found`

I created the file from the template and modified it just in case, but I have the same issue with any command.

### DOCKER COMPOSE
```
plex-music-ratings-sync:
    container_name: plex-music-ratings-sync
    hostname: plex-music-ratings-sync
    restart: on-failure
    networks:
      apps: {}
    logging:
      driver: json-file
      options:
        max-file: ${DOCKERLOGGING_MAXFILE}
        max-size: ${DOCKERLOGGING_MAXSIZE}
    environment:
      TZ: ${TZ}
      PUID: ${PUID}
      PGID: ${PGID}
    volumes:
      - ${DOCKER_DIR}/plex-music-ratings-sync:/app/data
      - ${DATA_DIR}/media:/data/media
    image: ghcr.io/rfgamaral/plex-music-ratings-sync
```

There are other services in the compose file that use the same variables to load environments, and those work correctly. But even if I specify paths manually, I get the same error.

### Command as per the README

```
docker compose run --rm plex-music-ratings-sync info
no configuration file provided: not found
```

```
docker compose run --rm plex-music-ratings-sync --help
no configuration file provided: not found
```

If there's something I'm missing, let me know.

Thank you so much for any help.
